### ISSUE TITLE
Thanks for this extension , one question

### ISSUE THREAD

**Issue by nkb-bd** [tomers/quasar-geolocation-example#1]
How to add this to my existing quasar project?

**Comment by tomers** [comment]
Thank you @nkb-bd  for your comment. I was surprised that indeed there is no information about the fact that this example uses an app extension I created. I'll fix that in the near future.
In the meanwhile, please review the extension's README at https://github.com/tomers/app-extension-geolocation, and use the example app as a reference for how to use it.

Please feel free to ask any further questions :-)

**Comment by nkb-bd** [comment]
Thanks :)
